Fixing metadata
ropensci/gutenbergr pull request #33
Opened 2022-11-04 18:51 UTC by msperlin

2022-11-04 18:52 UTC, msperlin commented
Hi, I justed fixed the python scripts and updated the metadata of the package. I also fixed the CHECK regarding download tests and roxygen version.

2022-11-04 19:00 UTC, noamross commented
Excellent, thank you @msperlin! @Myfanwy would you be able to take a look and test that everything runs and makes sense on your end for this?

2022-11-05 19:37 UTC, jonthegeek requested changes
Just one tiny typo in a comment, as far as I can tell.

I'm going to try to run checks to confirm that the results make sense, but so far it looks plausible, at least!

2022-11-05 19:37 UTC, jonthegeek commented on data-raw/01-download-metadata.sh
> +# Bash script for downloading and parsing metadata files from gutemberg.org
```suggestion
# Bash script for downloading and parsing metadata files from gutenberg.org
```

2022-11-05 19:55 UTC, jonthegeek requested changes
One other thing to make checks happier.

2022-11-05 19:55 UTC, jonthegeek commented on DESCRIPTION
> +RoxygenNote: 7.2.1
```suggestion
RoxygenNote: 7.2.1
Encoding: UTF-8
```

2022-11-05 19:55 UTC, jonthegeek commented on DESCRIPTION
> +RoxygenNote: 7.2.1
Specifying encoding to make roxygen2 happier.

2022-11-07 05:38 UTC, Myfanwy approved these changes
I agree with @jonthegeek's changes. The only other issues I ran in to were that the suggested `attr(gutenberg_metadata, "date_updated")` still returned the "2016-05-05" date of the previous metadata update, even though that attribute does update when I run code in-line from `data-raw/book_metadata.R`.  Also, building with `R CMD build gutenbergr` from the Terminal fails on the intro vignette for me, but I suspect that's user error on my part.  @jonthegeek  or @msperlin see if you can reproduce?

Apologies for any departures from convention(s) - first-time PR reviewer here

2022-11-07 10:57 UTC, msperlin commented
> 

Good morning @Myfanwy. I just reproduced the problem with the dates in `attr(gutenberg_metadata, "date_updated")` . To fix it, simply reinstall the package and the dates will show correctly:

![image](https://user-images.githubusercontent.com/10583352/200293854-8c9b6cb5-f68a-4f8d-9c41-ccde8f1ee2dc.png)

2022-11-07 10:58 UTC, msperlin commented
Your local repository had the previous gutenbergr version installed.

2022-11-07 11:09 UTC, msperlin commented
> Also, building with R CMD build gutenbergr from the Terminal fails on the intro vignette for me, but I suspect that's user error on my part. @jonthegeek or @msperlin see if you can reproduce?

Yes, and it worked fine here:

![image](https://user-images.githubusercontent.com/10583352/200295524-5793348d-ddb3-4fd1-a95f-fa6c9310a5a4.png)

I also ranned a local CHECK in Ubuntu 22.04 and it looks good:

![image](https://user-images.githubusercontent.com/10583352/200295951-927efc42-f10e-457e-ba05-fa22e6afd610.png)

I'm now implementing a GH CHECK action for Win/MAC and I'll post the results.

2022-11-07 12:01 UTC, msperlin commented
> I'm now implementing a GH CHECK action for Win/MAC and I'll post the results.

Unexpectedly, The GH action was not triggered in this PR. But I managed to run a CHECK in a local VM Win machine and it worked fine. I expect a positive result in a MAC, but it would be better if someone can confirm it (I don't have access to a MAC here..).

2022-11-07 21:30 UTC, Myfanwy commented
@msperlin after pulling the most recent commits to the fixing-metadata branch, the package builds and installs just fine (I was just missing a dependency before).  R CMD check on the built .tar.gz on my MAC yields 1 note:

```
checking data for non-ASCII characters ... NOTE
  Note: found 13617 marked UTF-8 strings
```
I am confident I can address this this week so I am tempted to merge.  @noamross & @jonthegeek, thoughts?

2022-11-07 21:45 UTC, msperlin commented
> @msperlin after pulling the most recent commits to the fixing-metadata branch, the package builds and installs just fine (I was just missing a dependency before). R CMD check on the built .tar.gz on my MAC yields 1 note:

> I am confident I can address this this week so I am tempted to merge. @noamross & @jonthegeek, thoughts?

Great. 

> @msperlin if you give me access permissions on the branch, I can push a change and test the GH action for the MAC?

Sure. I just added you to the repo. Let me know if I can help any further.

2022-11-08 13:35 UTC, jonthegeek requested changes
Delete the gutenbergr_0.2.0.tar.gz file (and then we'll squash-and-merge when we merge this to keep it out of the history). Having that file in version control can make it harder for people to get started contributing in the future, and there's no need. We'll probably include it in a *tag* later, but not in the main repo.

2022-11-08 18:03 UTC, jonthegeek approved these changes
This looks good!

Be sure to squash & merge (not just merge) when this one gets merged into master!

2022-11-08 21:07 UTC, merged